### PR TITLE
Mui 5

### PR DESCRIPTION
**Pull request by manav-06**

### CODE REVIEW

**Comment by adiXcodr** [comment]
@manav-06 was there a problem with the PR? I could not get the opportunity to review it

**Comment by manav-06** [comment]
I had the previous fork of the project. 

There was a merge conflict. When I resolved it, the styling got messed up.

**Comment by manav-06** [comment]
I will try resolve it.

**Comment by adiXcodr** [comment]
> I will try resolve it.

No issues. Reopen one when you're ready

**Pull request closed without merging**
